### ISSUE TITLE
启动服务器进程失败，求助！

### ISSUE THREAD

**Issue by TnmieUnas** [CrazyZhang666/EAappEmulater#6]
![屏幕截图(3)](https://github.com/user-attachments/assets/0f5b08c9-f2a0-4f80-b106-3ddc95cac85f)

表现为无法进入选择游戏启动的界面，bug反馈如下

异常类型: HttpListenerException
异常信息: 另一个程序正在使用此文件，进程无法访问。
堆栈调用: 
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at EAappEmulater.Core.BattlelogHttpServer.Run()
   at EAappEmulater.Core.Ready.Run()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at EAappEmulater.App.Main()

请问大概是哪个进程占用导致的创建网络进程失败？加速器什么的都关了

**Comment by TnmieUnas** [comment]
日志部分：
2024-07-25 13:17:48.1628 INFO 正在启动 LSX 监听服务... 
2024-07-25 13:17:48.1628 INFO 启动 LSX 监听服务成功 
2024-07-25 13:17:48.1628 INFO 正在启动 Battlelog 监听服务... 
2024-07-25 13:17:48.1628 INFO 正在检测新版本中...

**Comment by TnmieUnas** [comment]
我怀疑是不是版本检测的问题

**Comment by CrazyZhang666** [comment]
关闭和ea相关的任何软件，重启电脑后再试，这个是端口被占用导致的，下载最新版本模拟器

**Comment by TnmieUnas** [comment]
ea的都是关着的

**Comment by TnmieUnas** [comment]
重启后正常，感谢。ea相关的软件我一直都是关了，但不知道为什么还能端口占用，不知道是哪个软件干的
